spring:
  profiles: dev
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    timeout: 1000
    password:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mahjong?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: wsyzb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

security:
  oauth2:
    resource:
      filter-order: 3